### ISSUE TITLE
任务一的CodeReview

### ISSUE THREAD

**Issue by liwenzhusdu** [undefinedWebapp/ManagNotes#1]
hi,mozzie，我有两个问题
1、如果添加新的笔记分类，原来页面放不下，是要添加左右滑动吗?
2、新建笔记，是跳转到一个新页面?

**Comment by ferry1227** [comment]
@liwenzhusdu 关于以上2个问题我们已经讨论过了哈（0 0）
然后@All，我中午想了下数据结构，写成了API（数据结构）结构，如下图：
![addnote](https://cloud.githubusercontent.com/assets/7913724/8773582/c75c2cb0-2f07-11e5-93ec-1ad3b55a03a8.png)
![addnotetype](https://cloud.githubusercontent.com/assets/7913724/8773583/c76905f2-2f07-11e5-9083-1b2fc40777d3.png)

其中只放了新增的，还有修改的稍后发到讨论组。

大家有空先看下是否正确等，晚上再一起讨论下。

**Comment by MozzieH** [comment]
![Uploading addNotePage.png…]()

**Comment by ferry1227** [comment]
新增笔记页已使用markdown输入，待完成保存（笔记）的业务逻辑。
![addnotepage](https://cloud.githubusercontent.com/assets/7913724/8804490/156705e0-2fff-11e5-8061-ba936ffe054b.png)
